/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/coin.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/coin.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pCylinder7_standardSurface1_0.geometry} material={materials['gold-plate']} scale={[9.86, 1.458, 9.86]} />
    </group>
  )
}

useGLTF.preload('/coin.glb')
